server:
  port: 8080

spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create update none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect